baseURL: https://borovikovd.github.io
anguageCode: en-us
title: Blog of Denis Borovikov
theme: "PaperMod"

params:
  env: production

  homeInfoParams:
    Title: Hi there 👋
    Content: I am Denis Borovikov, engineer, manager and startup CTO. Welcome to my blog.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/denis_bvk/"
    - name: twitter
      url: "https://twitter.com/borovikov_en"
    - name: github
      url: "https://github.com/borovikovd"
